from turtle import *
from time import sleep

tim = Turtle()
tim.pensize(4)
bgcolor('#aaaaaa')
sleep(5)

tim.penup()
tim.goto(10, 150)
tim.color("#0000ff")
tim.write("Mr Earnshaw", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.forward(90)
tim.pendown()
tim.forward(70)
tim.penup()
tim.pendown()
tim.write("Mrs Earnshaw", font=("Arial", 12, "normal"))
tim.penup()
tim.setheading(180)
tim.forward(35)
tim.pendown()
tim.setheading(270)
tim.forward(30)
tim.setheading(180)
tim.forward(75)
tim.setheading(270)
tim.forward(20)
tim.penup()
tim.forward(40)
tim.setheading(180)
tim.forward(30)
tim.write("Cathrine\nEarnshaw", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.forward(30)
tim.setheading(90)
tim.forward(60)
tim.setheading(0)
tim.pendown()
tim.forward(150)
tim.setheading(270)
tim.forward(20)
tim.penup()
tim.forward(40)
tim.setheading(180)
tim.forward(30)
tim.write("Hendley\nEarnshaw", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.color("#800080")
tim.forward(60)
tim.pendown()
tim.forward(70)
tim.color("#ff00ff")
tim.write("Frances\nEarnshaw", font=("Arial", 12, "normal"))
tim.penup()
tim.setheading(180)
tim.forward(100)
tim.color("#0000ff")
tim.setheading(90)
tim.forward(60)
tim.setheading(180)
tim.forward(150)
tim.setheading(270)
tim.forward(60)
tim.setheading(180)
tim.forward(35)
tim.color("#00ff00")
tim.pendown()
tim.forward(70)
tim.color("#ffff00")
tim.penup()
tim.forward(50)
tim.write("Edgar\nLinton", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.forward(20)
tim.setheading(90)
tim.forward(40)
tim.pendown()
tim.forward(20)
tim.setheading(180)
tim.forward(150)
tim.setheading(270)
tim.forward(20)
tim.penup()
tim.forward(40)
tim.setheading(180)
tim.forward(30)
tim.write("Isabella\nLinton", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.forward(30)
tim.setheading(90)
tim.forward(60)
tim.setheading(0)
tim.forward(75)
tim.setheading(90)
tim.pendown()
tim.forward(30)
tim.setheading(180)
tim.forward(35)
tim.penup()
tim.forward(70)
tim.write("Mr Linton", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.forward(70)
tim.pendown()
tim.forward(70)
tim.penup()
tim.write("Mrs Linton", font=("Arial", 12, "normal"))
tim.setheading(180)
tim.forward(35)
tim.setheading(270)
tim.forward(30)
tim.setheading(180)
tim.forward(75)
tim.setheading(270)
tim.forward(60)
tim.setheading(180)
tim.forward(30)
tim.pendown()
tim.color("#ffbd00")
tim.forward(70)
tim.penup()
tim.forward(40)
tim.setheading(180)
tim.forward(30)
tim.color("#ff0000")
tim.write("Heathcliff", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.forward(100)
tim.setheading(270)
tim.pendown()
tim.color("#ffbd00")
tim.forward(30)
tim.penup()
tim.forward(40)
tim.setheading(180)
tim.forward(30)
tim.write("Linton\nHeathcliff", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.forward(30)
tim.setheading(90)
tim.forward(70)
tim.setheading(0)
tim.forward(250)
tim.color("#00ff00")
tim.forward(35)
tim.setheading(270)
tim.pendown()
tim.forward(30)
tim.penup()
tim.forward(40)
tim.setheading(180)
tim.forward(30)
tim.write("Cathrine\nLinton", font=("Arial", 12, "normal"))
tim.setheading(0)
tim.forward(30)
tim.setheading(90)
tim.forward(70)
tim.setheading(0)
tim.forward(250)
tim.color("#800080")
tim.forward(35)
tim.setheading(270)
tim.pendown()
tim.forward(30)
tim.penup()
tim.forward(40)
tim.setheading(180)
tim.forward(30)
tim.write("Hareton\nEarnshaw", font=("Arial", 12, "normal"))

mainloop()
